/* AUTOGENERATED FILE, DO NOT EDIT! 
   This file was produced by the following command:
  /home/peta/devel/terminalpp/build-release/stamp /home/peta/devel/terminalpp build-stamp.h
*/
#define STAMP helpers::Stamp("0.5.2", "5d6c188db0aebd3934352e6c272ef98aec211c3e", true,"2020-02-05T21:28:34Z")
