/* AUTOGENERATED FILE, DO NOT EDIT! 
   This file was produced by the following command:
   Debug\stamp.exe tpp/stamp.h
*/
#define STAMP helpers::Stamp("", "f2849ea2bd8d50842ee6c97b36cfd923710dd499", false,"2019-07-31T14:42:34Z")
