/* AUTOGENERATED FILE, DO NOT EDIT! 
   This file was produced by the following command:
   ./stamp terminalpp/stamp.h
*/
#define STAMP helpers::Stamp("0.4.4", "a0d32090aa57d5b1e70ba34912e23f8d4965a12d", false,"2019-11-01T20:30:03Z")
