/* AUTOGENERATED FILE, DO NOT EDIT! 
   This file was produced by the following command:
   Debug\stamp.exe terminalpp/stamp.h
*/
#define STAMP helpers::Stamp("0.4.4", "b9130dfbe24bcc44ea2f8f6ed11b59f6f45ef1d0", false,"2019-11-01T21:12:52Z")
