name: snapcraft-release-edge

on:
  push:
    branches:
      - release-edge

jobs:
  create-snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install-snapcraft
      run: |
        sudo chown root:root /
        sudo apt-get remove -qy lxd lxd-client
        sudo snap install lxd
        sudo lxd init --auto
        sudo snap install snapcraft --classic
    - name: login-snapcraft
      env:
        snapcraft_edge: ${{ secrets.snapcraft_edge }}      
      run: |
        echo $snapcraft_edge > snapcraft-edge-login
        snapcraft login --with snapcraft-edge-login
        rm snapcraft-edge-login
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev g++-8
    - name: build-snap
      run: |
        mkdir -p build/release
        cd build/release
        sudo cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=terminalpp -DSNAP_EXTRA_ARGS=--use-lxd
        sudo cmake --build . --target package-snap
    - name: release-to-snapcraft
      run: |
        sudo snapcraft push --release=edge build/release/packages/terminalpp.snap
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.snap
        path: build/release/packages/terminalpp.snap

